platform :ios, '8.0'

target 'Investment' do
	pod 'Masonry'
    #pod 'JSONModel'
    pod 'IQKeyboardManager'
    pod 'OpenUDID'
    pod 'Realm'
    pod 'LJContactManager'
    #pod 'LBXScan/LBXNative','~> 2.3'
    #pod 'LBXScan/LBXZXing','~> 2.3'
    #pod 'LBXScan/LBXZBar','~> 2.3'
    #pod 'LBXScan/UI','~> 2.3'

end
	
